fdfd.exe sphere_1.txt 
fdfd.exe sphere_2.txt 
fdfd.exe sphere_3.txt 
fdfd.exe sphere_4.txt 
fdfd.exe sphere_5.txt 
fdfd.exe sphere_6.txt 
fdfd.exe sphere_7.txt 
fdfd.exe sphere_8.txt 
fdfd.exe sphere_9.txt 
fdfd.exe sphere_10.txt
fdfd.exe sphere_11.txt
fdfd.exe sphere_12.txt
fdfd.exe sphere_13.txt
fdfd.exe sphere_14.txt
fdfd.exe sphere_15.txt
fdfd.exe sphere_16.txt
fdfd.exe sphere_17.txt
fdfd.exe sphere_18.txt
fdfd.exe sphere_19.txt
fdfd.exe sphere_20.txt
